# Generated by Django 5.0.4 on 2026-01-27 11:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the photos were generated')),
                ('num_photos', models.IntegerField(default=1, help_text='Number of input photos')),
                ('paper_size', models.CharField(default='A4', help_text='Paper size (A4, A3, Letter)', max_length=20)),
                ('orientation', models.CharField(default='portrait', help_text='Page orientation', max_length=20)),
                ('output_type', models.CharField(default='PDF', help_text='Output format (PDF or JPEG)', max_length=10)),
                ('output_path', models.CharField(help_text='Relative path to output file', max_length=500)),
                ('output_url', models.CharField(help_text='Public URL to download file', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, help_text='Size of generated file in bytes', null=True)),
                ('total_copies', models.IntegerField(default=1, help_text='Total number of photo copies in output')),
                ('user', models.ForeignKey(blank=True, help_text='User who generated the photos (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='generator_p_user_id_4c577a_idx'), models.Index(fields=['session_id'], name='generator_p_session_f952b0_idx')],
            },
        ),
    ]
