# Generated by Django 5.0.4 on 2026-01-29 02:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_userprofile_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, help_text="Feature name (e.g., 'crop', 'batch_upload', 'export_pdf')", max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the feature was used')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='How long the operation took', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional feature-specific data')),
            ],
            options={
                'verbose_name': 'Feature Usage',
                'verbose_name_plural': 'Feature Usage',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GenerationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('downloaded', 'Downloaded'), ('deleted', 'Deleted'), ('expired', 'Expired & Cleaned'), ('failed', 'Failed')], db_index=True, help_text='Action performed', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the requester')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the action')),
            ],
            options={
                'verbose_name': 'Generation Audit',
                'verbose_name_plural': 'Generation Audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generations_today', models.IntegerField(default=0, help_text='Number of generations today', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_size_today_mb', models.FloatField(default=0.0, help_text='Total size of generations today in MB', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_reset', models.DateTimeField(auto_now=True, help_text='Last time counter was reset')),
                ('is_blocked', models.BooleanField(db_index=True, default=False, help_text='Whether user is rate-limited')),
                ('block_reason', models.TextField(blank=True, help_text='Reason for blocking')),
                ('block_until', models.DateTimeField(blank=True, help_text='When the block expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When rate limit was created')),
            ],
            options={
                'verbose_name': 'User Rate Limit',
                'verbose_name_plural': 'User Rate Limits',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City/Town', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('UK', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('OTHER', 'Other')], default='IN', help_text='Country', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='landmark',
            field=models.CharField(blank=True, default='', help_text='Nearby landmark for easy location', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, default='', help_text='PIN/Postal Code', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_complete',
            field=models.BooleanField(default=False, help_text='Whether profile has all required fields'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('', '-- Select State --'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu & Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'), ('DL', 'Delhi')], default='', help_text='State/Province', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street_address',
            field=models.CharField(blank=True, default='', help_text='House number, street name', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the profile was created'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Phone number in E.164 format', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='generator_u_user_id_b3cb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='generator_u_created_eed4f2_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['postal_code'], name='generator_u_postal__9f2aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['country', 'state'], name='generator_u_country_088349_idx'),
        ),
        migrations.AddField(
            model_name='featureusage',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User using the feature', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_usage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generationaudit',
            name='generation',
            field=models.ForeignKey(help_text='Generation this audit entry relates to', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='generator.photogeneration'),
        ),
        migrations.AddField(
            model_name='generationaudit',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userratelimit',
            name='user',
            field=models.OneToOneField(help_text='User this rate limit applies to', on_delete=django.db.models.deletion.CASCADE, related_name='rate_limit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['feature', '-timestamp'], name='generator_f_feature_8d5456_idx'),
        ),
        migrations.AddIndex(
            model_name='featureusage',
            index=models.Index(fields=['user', '-timestamp'], name='generator_f_user_id_564417_idx'),
        ),
        migrations.AddIndex(
            model_name='generationaudit',
            index=models.Index(fields=['generation', '-timestamp'], name='generator_g_generat_186eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='generationaudit',
            index=models.Index(fields=['user', '-timestamp'], name='generator_g_user_id_ba8060_idx'),
        ),
        migrations.AddIndex(
            model_name='generationaudit',
            index=models.Index(fields=['action', '-timestamp'], name='generator_g_action_846993_idx'),
        ),
    ]
