# Generated by Django 5.0.4 on 2026-01-29 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_featureusage_generationaudit_userratelimit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_index', models.IntegerField(help_text='Index of photo in batch (0-based)')),
                ('photo_size', models.CharField(choices=[('passport_35x45', 'Passport (3.5×4.5 cm)'), ('passport_small', 'Small Passport (2.5×3.5 cm)'), ('id_card', 'ID Card (3.0×4.0 cm)'), ('visa_3x4', 'Visa (3.0×4.0 cm)'), ('visa_4x6', 'Visa Large (4.0×6.0 cm)'), ('uk_visa', 'UK Visa (4.45×5.59 cm)'), ('us_visa', 'US Passport (5.0×5.0 cm)'), ('schengen', 'Schengen (3.5×4.5 cm)'), ('australia', 'Australia (4.5×5.5 cm)'), ('canada', 'Canada (3.5×4.5 cm)'), ('custom', 'Custom Size')], default='passport_35x45', help_text='Selected photo size preset', max_length=30)),
                ('custom_width_cm', models.FloatField(blank=True, help_text="Custom width in cm (if photo_size is 'custom')", null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(20.0)])),
                ('custom_height_cm', models.FloatField(blank=True, help_text="Custom height in cm (if photo_size is 'custom')", null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(20.0)])),
                ('copies', models.IntegerField(default=1, help_text='Number of copies for this photo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('generation', models.ForeignKey(help_text='Generation this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photo_configs', to='generator.photogeneration')),
            ],
            options={
                'ordering': ['generation', 'photo_index'],
                'indexes': [models.Index(fields=['generation', 'photo_index'], name='generator_p_generat_d7e334_idx')],
                'unique_together': {('generation', 'photo_index')},
            },
        ),
    ]
