# Generated by Django 5.0.4 on 2026-02-01 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_photoconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generationaudit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the object was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='generationaudit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generationaudit',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Reason for deletion'),
        ),
        migrations.AddField(
            model_name='photogeneration',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the object was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='photogeneration',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deletions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photogeneration',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Reason for deletion'),
        ),
        migrations.CreateModel(
            name='DeletionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, help_text='Name of the model that was deleted/restored', max_length=100)),
                ('object_id', models.IntegerField(db_index=True, help_text='Primary key of the deleted/restored object')),
                ('action', models.CharField(choices=[('deleted', 'Soft Deleted'), ('restored', 'Restored'), ('hard_deleted', 'Permanently Deleted')], db_index=True, help_text='Action performed (deleted/restored/hard_deleted)', max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action was performed')),
                ('reason', models.TextField(blank=True, help_text='Reason for the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action')),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deletion History',
                'verbose_name_plural': 'Deletion History',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id', '-performed_at'], name='generator_d_model_n_602866_idx'), models.Index(fields=['performed_by', '-performed_at'], name='generator_d_perform_264233_idx'), models.Index(fields=['action', '-performed_at'], name='generator_d_action_7b603e_idx')],
            },
        ),
    ]
