# Generated by Django 5.0.4 on 2026-02-01 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_generationaudit_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_delete_days', models.IntegerField(default=30, help_text='Delete soft-deleted records older than N days')),
                ('last_cleanup', models.DateTimeField(blank=True, null=True)),
                ('total_deleted_records', models.IntegerField(default=0)),
                ('total_deleted_size_mb', models.FloatField(default=0)),
                ('cleanup_enabled', models.BooleanField(default=True, help_text='Enable automatic cleanup')),
            ],
            options={
                'verbose_name': 'System Maintenance',
                'verbose_name_plural': 'System Maintenance',
            },
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'User Login'), ('login_failed', 'Failed Login'), ('delete', 'Deleted Generation'), ('download', 'Downloaded File'), ('admin_action', 'Admin Action'), ('system', 'System Event')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity',
                'verbose_name_plural': 'Admin Activities',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='generator_a_timesta_3db80d_idx'), models.Index(fields=['action_type', '-timestamp'], name='generator_a_action__60911f_idx'), models.Index(fields=['user', '-timestamp'], name='generator_a_user_id_7db2c1_idx')],
            },
        ),
    ]
