# Generated by Django 5.0.4 on 2026-02-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_systemmaintenance_adminactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogeneration',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Error message if generation failed'),
        ),
        migrations.AddField(
            model_name='photogeneration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='completed', help_text='Processing status', max_length=20),
        ),
        migrations.AddField(
            model_name='photogeneration',
            name='task_id',
            field=models.CharField(blank=True, help_text='Background task ID (Celery)', max_length=255, null=True),
        ),
    ]
